services:
  - type: web
    name: gpt-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/wreyesgeopark/Prueba.git
    branch: master
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 