services:
  - type: web
    name: gpt-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/wreyesgeopark/Prueba.git
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: X_API_KEY
        value: x-api-key-WivKXD5Rfw5iYqijpDSqm_4EL6pMcc3QXeR9ZBuPyWE9wtwI 